# Generated by Django 2.2.5 on 2019-10-13 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientName',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=255, null=True)),
                ('title_n', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Dr', 'Dr')], default='', max_length=10, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('age', models.DecimalField(decimal_places=2, max_digits=5)),
                ('addult_child', models.CharField(blank=True, choices=[('ADULT', 'ADULT'), ('CHILD', 'CHILD')], default='', max_length=10, null=True)),
                ('p_h_g_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], default='', max_length=7, null=True)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('contact_no', models.DecimalField(decimal_places=0, max_digits=15)),
                ('foreigner_NRI', models.CharField(blank=True, choices=[('INDIAN', 'INDIAN'), ('NRI', 'NRI')], default='', max_length=50, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_of_country', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(default='defaultf.jpg', upload_to='patient_pics')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
