# Generated by Django 2.2.5 on 2019-10-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientname',
            name='foreigner_NRI',
            field=models.CharField(blank=True, choices=[('INDIAN', 'INDIAN'), ('NRI', 'NRI')], default='INDIAN', max_length=50, null=True),
        ),
    ]
