# Generated by Django 2.2.5 on 2019-10-13 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse', models.CharField(blank=True, max_length=500, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=500, null=True)),
                ('respiratory_rate', models.CharField(blank=True, max_length=500, null=True)),
                ('weight', models.CharField(blank=True, max_length=500, null=True)),
                ('temperature', models.CharField(blank=True, max_length=500, null=True)),
                ('mizaj_1', models.CharField(blank=True, max_length=500, null=True)),
                ('mizaj_2', models.CharField(blank=True, max_length=500, null=True)),
                ('date_vitals', models.DateTimeField(blank=True, null=True)),
                ('history_of_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientreg.PatientName')),
            ],
        ),
        migrations.CreateModel(
            name='PatientSystemic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respiratory_system', models.CharField(blank=True, max_length=500, null=True)),
                ('cardiovascular_system', models.CharField(blank=True, max_length=500, null=True)),
                ('abdomen', models.CharField(blank=True, max_length=500, null=True)),
                ('central_nervous_system', models.CharField(blank=True, max_length=500, null=True)),
                ('locomotor_system', models.CharField(blank=True, max_length=500, null=True)),
                ('local_examination', models.CharField(blank=True, max_length=500, null=True)),
                ('date_tested', models.DateTimeField(blank=True, null=True)),
                ('history_of_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientreg.PatientName')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProvisional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previsional_diagnosis', models.TextField(blank=True, max_length=500, null=True)),
                ('history_of_h', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patientreg.PatientName')),
            ],
        ),
        migrations.CreateModel(
            name='PatientObstetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('G', models.CharField(blank=True, max_length=500, null=True)),
                ('P', models.CharField(blank=True, max_length=500, null=True)),
                ('L', models.CharField(blank=True, max_length=500, null=True)),
                ('A', models.CharField(blank=True, max_length=500, null=True)),
                ('D', models.CharField(blank=True, max_length=500, null=True)),
                ('age_and_sex_child', models.CharField(blank=True, max_length=500, null=True)),
                ('method_of_delivery', models.CharField(blank=True, max_length=500, null=True)),
                ('nvd', models.CharField(blank=True, max_length=500, null=True)),
                ('lscs', models.CharField(blank=True, max_length=500, null=True)),
                ('immunization_of_children', models.CharField(blank=True, max_length=500, null=True)),
                ('history_of_c', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patientreg.PatientName')),
            ],
        ),
        migrations.CreateModel(
            name='PatientInvestigations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigations', models.TextField(blank=True, max_length=500, null=True)),
                ('history_of_g', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patientreg.PatientName')),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenting_complaints', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('history_of_presenting_complaints', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('department', models.CharField(blank=True, choices=[('General_Medicine', 'General Medicine'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Geriatrics', 'Geriatrics'), ('OBG', 'OBG'), ('Dermatology', 'Dermatology'), ('Urogenital', 'Urogenital'), ('ENT', 'ENT'), ('Orthopedics', 'Orthopedics'), ('Regimenal Therapy', 'Regimenal Therapy'), ('Other', 'Other')], default='', max_length=30, null=True)),
                ('past_historys', models.NullBooleanField(default='')),
                ('past_history_note', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('drug_history', models.NullBooleanField(default='')),
                ('drug_history_note', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('drug_allergies', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('treatment_history', models.NullBooleanField(default='')),
                ('treatment_history_note', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('surgeries', models.CharField(blank=True, max_length=500, null=True)),
                ('personal_history_sleep', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('personal_history_appetite', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('personal_history_diet', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('personal_history_bowel_bladder_habits', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('addictions', models.NullBooleanField(default='')),
                ('occupational_history', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('family_history', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('history_of_a', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patientreg.PatientName')),
            ],
        ),
        migrations.CreateModel(
            name='PatientGynaec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menarche', models.CharField(blank=True, max_length=500, null=True)),
                ('menopause', models.CharField(blank=True, max_length=500, null=True)),
                ('married_life', models.CharField(blank=True, max_length=500, null=True)),
                ('last_menstrual_period', models.CharField(blank=True, max_length=500, null=True)),
                ('flow', models.CharField(blank=True, max_length=500, null=True)),
                ('regularity', models.CharField(blank=True, max_length=500, null=True)),
                ('cycle', models.CharField(blank=True, max_length=500, null=True)),
                ('dysmenorrhea', models.CharField(blank=True, max_length=500, null=True)),
                ('clots', models.CharField(blank=True, max_length=500, null=True)),
                ('leucorrhea', models.CharField(blank=True, max_length=500, null=True)),
                ('history_of_b', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patientreg.PatientName')),
            ],
        ),
        migrations.CreateModel(
            name='PatientGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('built_and_nourishment', models.CharField(blank=True, max_length=500, null=True)),
                ('pallor', models.CharField(blank=True, max_length=500, null=True)),
                ('edema', models.CharField(blank=True, max_length=500, null=True)),
                ('cyanosis', models.CharField(blank=True, max_length=500, null=True)),
                ('clubbing', models.CharField(blank=True, max_length=500, null=True)),
                ('icterus', models.CharField(blank=True, max_length=500, null=True)),
                ('lymphadenopathy', models.CharField(blank=True, max_length=500, null=True)),
                ('history_of_d', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patientreg.PatientName')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filal_Diagnosis', models.TextField(blank=True, max_length=500, null=True)),
                ('date_diagnosis', models.DateTimeField(blank=True, null=True)),
                ('history_of_i', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patientreg.PatientName')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.TextField(blank=True, max_length=500, null=True)),
                ('date_visited', models.DateTimeField(blank=True, null=True)),
                ('history_of_j', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientreg.PatientName')),
            ],
        ),
    ]
